project:
  type: website

website:
  title: "Language Data Wrangling Guides"
  navbar:
    left:
      - data_modelling/index.qmd
      - text: "Data Preparation Workbench"
        href: data_preparation_workbench/index.qmd
      - text: "Data Formats Reference"
        href: data_format_reference/index.qmd
    right:
      - about.qmd
      - href: https://www.ldaca.edu.au
        text: LDACA
  search: true
  sidebar:
    - title: "Data Preparation Workbench"
      contents:
      - data_preparation_workbench/index.qmd
      - data_preparation_workbench/guide_to_text.qmd
      - data_preparation_workbench/guide_to_audio.qmd
      - section: "Getting Started Guides"
        contents:
        - data_preparation_workbench/choosing_a_format_for_working.qmd
        - data_preparation_workbench/choosing_a_format_for_publishing.qmd
        - data_preparation_workbench/choosing_a_format_for_archiving.qmd
      - section: "How To Guides"
        contents:
        - data_preparation_workbench/conversion.qmd
        - data_preparation_workbench/wrangling.qmd
        - data_preparation_workbench/publishing_archiving.qmd
        - data_preparation_workbench/automating.qmd
    - title: "Data Formats Reference"
      contents:
      - data_format_reference/index.qmd
      - data_format_reference/types.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



